### ISSUE TITLE
Error check for wpt line format

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#57] opened 2017-07-30 03:12 UTC
These lines got into mn.mn298.wpt, which caused the site update to fail:

```
+x01 http://www.openstreetmap.org/?lat=19/44.28690&lon=-93.25970
+x02 http://www.openstreetmap.org/?lat=19/44.28646&lon=-93.25973
+x03 http://www.openstreetmap.org/?lat=19/44.28644&lon=-93.25929
MottAve http://www.openstreetmap.org/?lat=19/44.28694&lon=-93.25901
```
Unfortunately, the site update did not crash until during DB update, leaving the site offline.

Need to add in checks for when a wpt is read and the lines cannot be parsed properly and flag those as errors earlier in the update process.

**Comment by ajfroggie** [comment] 2017-07-30 03:20
Thought I caught those....oops.  Downside of our format and how it differs from default OSM URLs...

**Comment by ajfroggie** [comment] 2017-07-30 03:21
Are you fixing those or should I?

**Comment by jteresco** [comment] 2017-07-30 03:40
Just pushed up the fixed file.  Fortunately just lines in that one file had the error.

**Comment by yakra** [comment] 2018-11-06 20:47
A .wpt line containing only whitespace crashes siteupdate.py. (A newline only, sans whitespace, is OK.)
siteupdate.py stops reading in remaining Waypoints from the offending, or future, .wpt files, proceeds thru writing graphs (of this partial dataset), and crashes when trying to perform the first of the main datachecks.

**Comment by yakra** [comment] 2018-12-21 00:13
> Unfortunately, the site update did not crash until during DB update, leaving the site offline.

Interesting. I made a small program to test this, and it crashed immediately upon attempting the string->float conversion with bad input. If you indeed got different results, I'll just chalk it up to more differences between the FreeBSD & Ubuntu flavours of Python.

---
**Current code:**
https://github.com/TravelMapping/DataProcessing/blob/dc8a05c0968abaee8b136305c5e5118fdcdbb84c/siteupdate/python-teresco/siteupdate.py#L267-L272
Execution time:
* 104.775 s single-threaded, 115.95 s multi-threaded on noreaster
* 127.85 s single-threaded, 191.025 s multi-threaded on BiggaTomato
---
**Option 1:**
```Python
        # last has the URL, which needs more work to get lat/lng
        url_parts = parts[-1].split('=')
        lat_string = url_parts[1].split("&")[0] # chop off "&lon"
        lng_string = url_parts[2].split("&")[0] # chop off possible "&zoom"

        # make sure lat_string is valid
        point_count = 0
        for c in range(len(lat_string)):
            # check for multiple decimal points
            if lat_string[c] == '.':
                point_count += 1
                if point_count > 1:
                    datacheckerrors.append(DatacheckEntry(route,[self.label],'MALFORMED_URL', parts[-1]))
                    lat_string = "0"
                    lng_string = "0"
                    break
            # check for minus sign not at beginning
            if lat_string[c] == '-' and c > 0:
                datacheckerrors.append(DatacheckEntry(route,[self.label],'MALFORMED_URL', parts[-1]))
                lat_string = "0"
                lng_string = "0"
                break
            # check for invalid characters
            if lat_string[c] not in "-.0123456789":
                datacheckerrors.append(DatacheckEntry(route,[self.label],'MALFORMED_URL', parts[-1]))
                lat_string = "0"
                lng_string = "0"
                break

        # make sure lng_string is valid
        point_count = 0
        for c in range(len(lng_string)):
            # check for multiple decimal points
            if lng_string[c] == '.':
                point_count += 1
                if point_count > 1:
                    datacheckerrors.append(DatacheckEntry(route,[self.label],'MALFORMED_URL', parts[-1]))
                    lng_string = "0"
                    break
            # check for minus sign not at beginning
            if lng_string[c] == '-' and c > 0:
                datacheckerrors.append(DatacheckEntry(route,[self.label],'MALFORMED_URL', parts[-1]))
                lng_string = "0"
                break
            # check for invalid characters
            if lng_string[c] not in "-.0123456789":
                datacheckerrors.append(DatacheckEntry(route,[self.label],'MALFORMED_URL', parts[-1]))
                lng_string = "0"
                break

        self.lat = float(lat_string)
        self.lng = float(lng_string)
```
Execution time:
* 110.275 s single-threaded, 121.075 s multi-threaded on noreaster
  - adding 5.5 s & 5.125 s respectively, compared to reference
* 134.8 s single-threaded, 199.745 s multi-threaded on BiggaTomato
  - adding 6.95 s & 8.45 s respectively, compared to reference
---
**Option 2:**
```Python
        # last has the URL, which needs more work to get lat/lng
        url_parts = parts[-1].split('=')
        lat_string = url_parts[1].split("&")[0] # chop off "&lon"
        lng_string = url_parts[2].split("&")[0] # chop off possible "&zoom"

        # make sure lat_string is valid
        for c in range(len(lat_string)):
            # check for minus sign not at beginning
            if lat_string[c] == '-' and c > 0:
                datacheckerrors.append(DatacheckEntry(route,[self.label],'MALFORMED_URL', parts[-1]))
                lat_string = "0"
                lng_string = "0"
                break
            # check for invalid characters
            if lat_string[c] not in "-.0123456789":
                datacheckerrors.append(DatacheckEntry(route,[self.label],'MALFORMED_URL', parts[-1]))
                lat_string = "0"
                lng_string = "0"
                break
        # check for multiple decimal points
        ptpos = lat_string.find('.')
        if ptpos != -1:
            if lat_string.find('.', ptpos+1) != -1:
                datacheckerrors.append(DatacheckEntry(route,[self.label],'MALFORMED_URL', parts[-1]))
                lat_string = "0"
                lng_string = "0"

        # make sure lng_string is valid
        for c in range(len(lng_string)):
            # check for minus sign not at beginning
            if lng_string[c] == '-' and c > 0:
                datacheckerrors.append(DatacheckEntry(route,[self.label],'MALFORMED_URL', parts[-1]))
                lng_string = "0"
                break
            # check for invalid characters
            if lng_string[c] not in "-.0123456789":
                datacheckerrors.append(DatacheckEntry(route,[self.label],'MALFORMED_URL', parts[-1]))
                lng_string = "0"
                break
        # check for multiple decimal points
        ptpos = lng_string.find('.')
        if ptpos != -1:
            if lng_string.find('.', ptpos+1) != -1:
                datacheckerrors.append(DatacheckEntry(route,[self.label],'MALFORMED_URL', parts[-1]))
                lng_string = "0"

        self.lat = float(lat_string)
        self.lng = float(lng_string)
```
Execution time:
* 110.2 s single-threaded, 121.05 s multi-threaded on noreaster
  - adding 5.425 s & 5.1 s respectively, compared to reference
* 135.4 s single-threaded, 200.825 s multi-threaded on BiggaTomato
  - adding 7.55 s & 9.8 s respectively, compared to reference
---
On **noreaster**, Option 2 is faster than Option 1 by 0.075 s single-threaded, 0.025 s multi-threaded. Not much difference; could well be within margin of error.
On **BiggaTomato**, Option 1 is faster than Option 2 by 0.6 s single-threaded, 1.35 s multi-threaded. A more clear lead, here. That and I think the code looks tidier and easier to follow.
**Option 1** it is.

**Next up:**
Adding a check for too few parts to the URL, E.G. `http://www.openstreetmap.org/?lat=44.291495`
I'll see if that also has any effect on whitespace-only lines as noted in my previous comment.

**Comment by jteresco** [comment] 2018-12-21 21:35
I think the difference that has mattered in terms of the site update attempting to continue is because on FreeBSD if a wpt has a line that causes a thread to throw an exception, that thread dies, but the others continue, including the original master thread which will never know something happened.

**Comment by yakra** [comment] 2018-12-22 07:56
I was just about to suggest the same thing, then noticed you beat me to it.
I've seen the same behaviour on Ubuntu.
*Part* of the program crashes right away. For the *overall* program to crash, that takes a little more time.

**Comment by yakra** [comment] 2018-12-23 05:42
With the issue in the OP addressed, good to mark closed?

**Comment by jteresco** [comment] 2018-12-23 15:51
Yes, I think so, so I'll close.  Thanks for the work on this!

**Comment by michihdeu** [comment] 2018-12-23 16:06
What happens if the line is wrong?
What's output in siteupdate.log?
What happens to the route, will it be removed from the system?

**Comment by yakra** [comment] 2018-12-23 18:04
If the line is wrong, the route stays in the system. The individual point stays, but since latitude & longitude cannot be parsed, both are set to 0, and a MALFORMED_URL datacheck will be flagged in [datacheck.php](http://travelmapping.net/devel/datacheck.php) and [datacheck.log](http://travelmapping.net/logs/datacheck.log). Nothing is output to siteupdate.log itself; siteupdate just continues on without a thread throwing an exception and dying.

**Comment by michihdeu** [comment] 2018-12-23 18:15
Thanks. But it makes caring for datacheck more important. I wish more contributors would care about it and fix them. If it would be output in siteupdate.log (and Bash), one would directly see this critical error...

**Comment by yakra** [comment] 2018-12-23 18:48
> I wish more contributors would care about it and fix them.

I definitely agree there.

At least in this case, a look at the HB will quickly show that things are out of whack, since the nearest point on land to (0.000000°, 0.000000°) is > 360 miles away.
I opted to not create more work for Jim in repairing data when site updates fail due to this rare error. (I'm not aware of this error happening before or since the case Jim mentioned in the OP.)

If it's useful, we could also have a warning output to Bash when the datacheck is flagged.

**Comment by jteresco** [comment] 2018-12-23 18:57
Given additional discussion, I'll reopen for now.

Thinking about this some more, I worry about letting a site update run to completion with such an error indicated by the point moving to (0,0).  That would really skew the stats and as @michihdeu reminds, not everyone goes back and checks that their changes were good and as intended after making submissions.

I'm wondering if this would better be handled either by ignoring the point, ignoring the route, or even make it a fatal error in the site update.  I think that last approach would definitely catch them right away for users who run datacheck.sh consistently, but as @yakra points out, make a bit of extra fixup work for me when a bad file gets in without having passed datacheck.sh.

**Comment by michihdeu** [comment] 2018-12-23 19:02
Warning would be fine. Maybe that's an option for all "critical" data errors like "DUPLICATE_LABEL", "LABEL_INVALID_CHAR" or "OUT_OF_BOUNDS"?

**Comment by yakra** [comment] 2018-12-24 06:52
> not everyone goes back and checks that their changes were good and as intended after making submissions.

While this is true, my view is this will be a big, glaring error immediately obvious to anyone who opens up the route in the HB. If not the original contributor, *somebody* should find it, and hopefully report it in the forum. These rare errors should in practice be short-lived.

> > I'm wondering if this would better be handled either by ignoring the point, ignoring the route, or even make it a fatal error in the site update
>
> Ignoring the point or even the route is definitely better than moving the point to 0,0.

I don't like the idea of ignoring the route. Too transparent a failure mode IMO; too easy to not notice something's amiss.
That, and it breaks more than just a single point.

> I'd prefer ignoring the point in combination to the warning output and (red) data check error displayed on the site.

This is easily workable. Only needs minor changes to the code as-is now.
We can have the error listed in dataceck, even with the ignored point not making it into the HB.
Contributors can see there's a datacheck item, and then go to the source .wpt file -- which is where they'd have to go anyway to fix the error. :)

**How To...**
Right now, in the `Route.read_wpt` function, we have:
```Python
w = Waypoint(line,self,datacheckerrors)
self.point_list.append(w)
```
Just gotta change it to
```Python
w = Waypoint(line,self,datacheckerrors)
if w.is_valid() == True:
    self.point_list.append(w)
```
...and write a `Waypoint.is_valid()` function.
How do we tell if a waypoint is valid? I'm loathe to add a new variable to the Waypoint class & take up more RAM if we don't have to. We could leverage the new code added in #153, and have coords of (0.0°,0.0°) denote an invalid point. Thus the 0,0 coords would just be used internally, temporarily, and the point would not make it to the DB or HB.
We'd get our datacheck error, and ignore the point. Adding a warning to the siteupdate log is easy too.

---

As an aside, I don't consider OUT_OF_BOUNDS a critical error, [or a datacheck_always_error](https://github.com/TravelMapping/DataProcessing/pull/128). Circumstances where there'd be false positives are conceivable, roads spanning +/-180°. Imagine that West Coast Road, Taveuni, Fiji were a numbered route.

**Comment by michihdeu** [comment] 2018-12-24 07:57
I think I got OUT_OF_BOUNDS wrong. It's fine to me.

I cannot tell you what's the best and most efficient way... _I really don't care about RAM usage in backend progress during site update / contributor data check - in opposition to frontend / user end - but I understand that it's important to you. For instance, I also hate not clearly arranged code_ 😆 ,,,but I'm quite sure that many contributors just don't care about data errors. Just don't check it during one's own data check run nor on the site the next day. Not everyone is a NERD like... well, me.... so, it's also fine but critical errors might slip through and might have a big influence on user end. And a 0,0 wp is a big influence because system/region stats are changed and normal user just wonder what happened. I would not trust that any user would notice it at all and report it on the forum, e.g. if a new route is added to... IDN, RUS or whatever "remote" place...

I press CTRL+S to save my wpt file. Sometimes I had missed the CTRL button and had entered a "s" anywhere in the file by accident. When I copy the wps from wpt editor to the file, I press CTRL+A and CTRL+C. It happened that I had "ac" at the end of the line for the same reason. Jim noticed and fixed it during site update, now I can catch it because my own data check fails. But when you "hide" it as a normal data error, I need to check datacheck.log. I don't check it after every run just because there are too many entries in the log and I need to search the whole file (half-automated only because search is always in one direction).

btw: Would it be possible to output in Bash all new data errors caused by my latest changes? We could compare the new datacheck.log to the previous one but it's just my file. The old version is from my last run and all other new data errors caused by anyone else would be output too. But if there would be a way to get the last version from the "official" datacheck.log..... Maybe an options once we would have automated site updates? Just dreaming..... 😃

**Comment by yakra** [comment] 2018-12-24 20:59
After my post last night I worked on a solution as described above, one that would output an error in Bash / siteupdate.log, flag a datacheck error, and ignore the point.

A dry run ran to completion on noreaster, no crashes, last night just before I went to sleep.
A "normal" run with no errors intentionally created, just to compare against the output from the "official" siteupdate.py, and make sure nothing's newly broken. Still have to check the output, then break stuff and check *that* output too.

> I press CTRL+S to save my wpt file. Sometimes I had missed the CTRL button and had entered a "s" anywhere in the file by accident.

[Done that.](https://github.com/TravelMapping/HighwayData/blame/62c53d9490049fe0aefe8a0366e51ea779e344f5/hwy_data/TX/usaus/tx.us083.wpt#L1)

> When I copy the wps from wpt editor to the file, I press CTRL+A and CTRL+C. It happened that I had "ac" at the end of the line for the same reason. Jim noticed and fixed it during site update, now I can catch it because my own data check fails.

OK yeah, I see what you mean -- `http://www.openstreetmap.org/?lat=25.883169&lon=-97.476363ac` has no `&` after the longitude number, means we don't `chop off possible "&zoom"`, means `lng_string` = `-97.476363ac`, which has invalid characters and won't get parsed at all.
If I "hide" this as a normal data error, it's too transparent a failure mode.

> I need to check datacheck.log. I don't check it after every run just because there are too many entries in the log

Yeah, the signal-to-noise ratio is pretty poor...

---

> btw: Would it be possible to output in Bash all new data errors caused by my latest changes? We could compare the new datacheck.log to the previous one but it's just my file. The old version is from my last run and all other new data errors caused by anyone else would be output too. But if there would be a way to get the last version from the "official" datacheck.log..... Maybe an options once we would have automated site updates? Just dreaming..... 😃

#155

**Comment by yakra** [comment] 2018-12-24 21:37
> Right now, in the `Route.read_wpt` function, we have:
> ```Python
> w = Waypoint(line,self,datacheckerrors)
> self.point_list.append(w)
> ```
> Just gotta change it to
> ```Python
> w = Waypoint(line,self,datacheckerrors)
> if w.is_valid() == True:
>     self.point_list.append(w)
```
...by which I mean,
```Python
w = Waypoint(line,self,datacheckerrors)
if w.is_valid() == False:
    continue
self.point_list.append(w)
```
;P

**Comment by yakra** [comment] 2018-12-24 23:00
> Right now, in the `Route.read_wpt` function, we have:
> ```Python
> w = Waypoint(line,self,datacheckerrors)
> self.point_list.append(w)
> ```
> Just gotta change it to
> ```Python
> w = Waypoint(line,self,datacheckerrors)
> if w.is_valid() == True:
>     self.point_list.append(w)
>```
...by which I mean,
```Python
w = Waypoint(line,self,datacheckerrors)
if w.is_valid() == False:
    w = previous_point
    continue
self.point_list.append(w)
```
;P
But this still isn't working as expected; with the data I'm testing, I broke the URLs in all seven point of ME226.
I should see an error message, but don't...
```Python
if len(r.point_list) < 2:
    el.add_error("Route contains fewer than 2 points: " + str(r))
```

I'll look into this more after Christmas.
In the meantime, Merry Christmas everybody!

**Comment by yakra** [comment] 2018-12-28 06:43
```DIFF
[yakra@noreaster ~/tm2/DataProcessing/siteupdate/python-teresco]$ diff all_waypoints.reference.log all_waypoints.issue57.log 
317597,317600d317596
< me.me226 BarRd (0.0,0.0)
< me.me226 BirRd (0.0,0.0)
< me.me226 KinSt (0.0,0.0)
< me.me226 ME27 (0,0)
```

**Comment by yakra** [comment] 2018-12-28 07:45
@michihdeu wrote:
> Warning would be fine.
...
I'd prefer ignoring the point in combination to the warning output and (red) data check error displayed on the site.

With my latest revision (pull request not opened yet):
* MALFORMED_URL points are ignored.
* [Datacheck errors are logged](http://yakra.teresco.org/logs/issue57/datacheck.log). (search for `me.me090`) Turning them red in datacheck.php, I believe @jteresco would have to handle on the Web end.
* warning output in Bash & [siteupdate.log](http://yakra.teresco.org/logs/issue57/siteupdate.log). (search for `me.me090`) The downside here is that the warnings appear when reading in the WPT files, and scroll up off the top of the screen. You'd have to be closely watching Bash when running siteupdate.py, or check siteupdate.log after the process completes to catch these. If this is a deal-breaker, I have an idea about how to address this...

**Comment by michihdeu** [comment] 2018-12-28 07:59
> MALFORMED_URL points are ignored.

What does "ignore" mean? The wp is omitted? What happens if it's the last / first wp? Does it just "not exist" (route truncated) or might there be any problem?

> Datacheck errors are logged (search for me.me090). Turning them red in datacheck.php, I believe @jteresco would have to handle on the Web end.

I think red is default: https://github.com/TravelMapping/Web/blob/master/devel/datacheck.php#L42
No action required.

> If this is a deal-breaker, I have an idea about how to address this...

Errors are also output where it happens and [in addition at the end (example)](https://github.com/TravelMapping/HighwayData/pull/2437#issuecomment-449491054).

**Comment by michihdeu** [comment] 2018-12-28 08:09
It's called [ErrorList](https://github.com/TravelMapping/DataProcessing/blob/master/siteupdate/python-teresco/siteupdate.py#L31) and you just need to call `el.add_error`. But I don't know the consequences when we add the "warning" to the error list. It should not stop the run and there should still be "[Data check successful!](https://github.com/TravelMapping/DataProcessing/blob/master/siteupdate/python-teresco/siteupdate.py#L3689)" output at the end.

**Comment by yakra** [comment] 2018-12-28 18:20
> What does "ignore" mean? The wp is omitted?

Completely omitted. It doesn't get added to the Route object, or the DB, or the HB, or inserted into the Quadtree.

> What happens if it's the last / first wp? Does it just "not exist" (route truncated) or might there be any problem?

Just doesn't exist; route truncated. If this brings the total number of points in the Route down to less than two, then it triggers an `ErrorList` [error](https://github.com/TravelMapping/DataProcessing/issues/57#issuecomment-449776847), and siteupdate eventually aborts.

> Errors are also output where it happens and [in addition at the end (example)](https://github.com/TravelMapping/HighwayData/pull/2437#issuecomment-449491054).

Normally, when we use the ErrorList, yes. If any fatal errors are detected, siteupdate aborts before performing the datachecks, and lists all the errors.
This is not the case here, as these warnings are just "WARNING"s, designed to not stop the run.

> It's called [ErrorList](https://github.com/TravelMapping/DataProcessing/blob/master/siteupdate/python-teresco/siteupdate.py#L31) and you just need to call `el.add_error`. But I don't know the consequences when we add our "warning" to the error list. It should not stop the run and there should still be "[Data check successful!](https://github.com/TravelMapping/DataProcessing/blob/master/siteupdate/python-teresco/siteupdate.py#L3689)" output at the end. **Maybe we just need a copy of ErrorList, a WarningList?** I don't know what's the most efficient way. I don't like ending up with unclear overhead code...

Exactly what I was thinking.
The existing `el` can be or list of fatal errors, which stops siteupdate.
A new `wl` can track our non-fatal warnings.

I don't think this is worth adding a new class for, when the existing ErrorList class will do.
All we'd really need to change is to have `ErrorList.add_error` output "WARNING: " to Bash instead of "ERROR: ", so we can tell the two apart. There are a couple ways to do this:
1. Add a new `add_warning` function, which works the same as `add_error`, but just prints "WARNING: " to Bash instead of "ERROR: ".
2. Change `add_error` to take a second string denoting what's being added to the `error_list`. This new string could be "ERROR", "WARNING", "NOTICE", "POTRZEBIE", whatever we want; all we'd be doing with it is printing it to Bash. I see this method as being more extensible. We'd just have to change the existing calls to `el.add_error`.
By way of clarity & code organization, we may want to rename `add_error` to simply `add`, as we could be adding not just errors, but also warnings, etc. EG:
`el.add("ERROR", "System mismatch parsing line [" + line + "], expected " + system.systemname)`
`wl.add("WARNING", "Malformed URL in " + route.root + ", line: " + line)`

We'd need to output the contents from `wl` in two places:
1. If there are items in `el`, output the warnings along with the errors when siteupdate aborts.
2. If not, and siteupdate proceeds to the end ("Data check successful!"), output the warnings to Bash at the very end of the siteupdate process, where we can't miss them.

@jteresco, your thoughts on this?

**Comment by michihdeu** [comment] 2018-12-28 18:43
Thanks. Warning should also being output to siteupdate.log

About log levels: https://en.wikipedia.org/wiki/Log4j#Log4j_log_levels

**Comment by yakra** [comment] 2018-12-28 18:55
> Thanks. Warning should also being output to siteupdate.log

Yes. siteupdate.log is produced by piping the output of siteupdate.py to tee, so what's written to Bash is thereby written to siteupdate.log too.

> About log levels: https://en.wikipedia.org/wiki/Log4j#Log4j_log_levels

I don't see how this has any relevance to siteupdate.

**Comment by michihdeu** [comment] 2018-12-28 19:02
> I don't see how this has any relevance to siteupdate.

> This new string could be "ERROR", "WARNING", "NOTICE", "POTRZEBIE", whatever we want;

Maybe errors should be FATAL and warnings ERROR?
Maybe errors should be ERROR and warnings INFO?

**Comment by yakra** [comment] 2018-12-28 19:16
I don't see the need to conform the the standards of a utility that's not used in the TM project. IMO, this would just make things less clear.
Recall that the only purpose of this new string for `add_error` is to be printed to Bash & provide info for the user.
>  Maybe errors could be ERROR and warnings INFO?

I think "WARNING" would be a more clear indication than "INFO" that we're dealing with bad data in need of attention/fixes.

**Comment by jteresco** [comment] 2018-12-28 20:01
I don't see the need to go beyond "error" and "warning".  I do like the idea of being able to flag non-fatal warnings and have them be reported in a clear and convenient place at the end of the run.  But to some extent, isn't that what the datacheck.log is for?

**Comment by michihdeu** [comment] 2018-12-28 20:05
> But to some extent, isn't that what the datacheck.log is for?

yes, but the file does currently have more than 3,000 lines. We talk about indicating the changed data errors caused by the current update.

**Comment by michihdeu** [comment] 2018-12-28 20:06
> I don't see the need to go beyond "error" and "warning".

Me too. I was also surprised by "whatever" and just thought we should not create our own log levels. I'm fine with error and warning.

**Comment by jteresco** [comment] 2018-12-28 20:08
I think siteupdate.py can't be the place for things specifically caused by a current update.  It needs to ingest all of the highway and user data and create what it needs to update the site based on that.  If we make all or even some of the datachecks into warnings that get printed at the end, I think it will also end up being an unreasonably long list given how little attention is sometimes paid to addressing datacheck problems.

**Comment by michihdeu** [comment] 2018-12-28 20:12
That's the point. When there are already so many data errors, no one really cares anymore. As mentioned before, Bash output could be an option (argument?) to the command for executing datacheck.sh.

**Comment by jteresco** [comment] 2018-12-28 21:22
But will anyone who doesn't look at the regular datachecks look at the log?  Mainly I just want to avoid too much duplication.

As a general rule, I'd like to thin out some of the output generated by siteupdate.py to things like meaningful warnings will be easier to notice.

**Comment by jteresco** [comment] 2018-12-29 04:01
Would the following be helpful?  Have all datacheck errors in active systems and all "red" errors in preview systems listed in the output and at the end of siteupdate.log.

**Comment by yakra** [comment] 2018-12-29 07:20
Whoops. Glossed over Jim's last 2 replies before I posted.

> But will anyone who doesn't look at the regular datachecks look at the log? Mainly I just want to avoid too much duplication.

Agreed, as noted above.

> As a general rule, I'd like to thin out some of the output generated by siteupdate.py to **[sic]** *(so?)* things like meaningful warnings will be easier to notice.

Keeping it its existing thinness, and not adding any new, arguably extraneous, info, I can certainly dig.
Thinning it out further is another kettle of fish, another topic perhaps. *Not much* comes to mind immediately.
**Off-topic:** the C++ siteupdate runs fast enough that we could possibly get away with, during reading in WPT files, not printing a system name followed by a `.` for each route, but just a `.` for each system.

> Would the following be helpful? Have all datacheck errors in active systems and all "red" errors in preview systems listed in the output and at the end of siteupdate.log.

IMO, no. Duplication. This info is available in datacheck.log & on the datacheck page, and I can get it there.
I considered it a bit, but I started counting "red" errors in preview systems on datacheck.php. Stopped counting at 70. Adds too much noise to the signal for my taste.
Seems that running a DIFF of existing vs new datacheck.log may be a more "signal-to-noise friendly" way to get this info for "power users" like us in this thread.

I'll echo what michih said earlier:
> I wish more contributors would care about [datacheck entries] and fix them.

**Comment by michihdeu** [comment] 2018-12-29 07:48
> Would the following be helpful? Have all datacheck errors in active systems and all "red" errors in preview systems listed in the output and at the end of siteupdate.log.

No, I'm with yakra.

> If people ignore the datacheck items, they may also ignore lines logged at the end of siteupdate's output. And we could end up with an unreasonably long list...

I'm not sure that you got me right. I only wanna output the DIFFs. This should usually be a very, very small list.
I can enter the command manually but:

> Having DIFFs of new datacheck entries done by default in datacheck.sh, OTOH, could provide a small kick in the pants by bringing the info to a contributor's attention, without having it become part of the "permanent" siteupdate.py output.

This!

**Comment by yakra** [comment] 2018-12-31 05:12
In the OP, @jteresco wrote:
> Need to add in checks for when a wpt is read and the lines cannot be parsed properly and flag those as errors earlier in the update process.

Datachecks for malformed URLs are implemented.
Anything before the URL is part of a label; all we'd really have to worry about there is invalid characters; discussion for that is at #41.
#158 takes care of ignoring points with malformed URLs, as discussed upthread.
The only other outstanding issue is that of warning text when these errors encountered. It seems the current thinking on that is moving more toward using DIFFs to list new datacheck entries. If so, that can be discussed at #155.

I'd like to merge #158 in and re-close this. OK to do so?

**Comment by yakra** [comment] 2019-10-25 23:57
Reopening, now that I see an example playing out in the real world.
`rou.dj102k;DC73B;;;MALFORMED_URL;http://www.openstreetmap.org/?la`

### info value
The `value` column in the DB (displayed in the `info` column on the datacheck.php webpage) only stores 32 characters. Thus our URL gets truncated to a useless `http://www.openstreetmap.org/?la`. Rather than lengthen the field to store more data, I think it makes sense to just drop the info column for a MALFORMED_URL error. It doesn't help us any; the contributor can just look up the offending WPT line by the waypoint label.

### C++ / MySQL 8.0
In theory, on lab2, we wouldn't even be able to insert the overlength info string into the table: MySQL 8.0 will simply refuse to do so, rather than truncate. But on lab2, there's no datacheck error...
I never implemented MALFORMED_URL in the C++ siteupdate program, because C++ has a more robust string->float conversion function than what we're using in Python: Python requires that all characters in the string to be converted be valid: `0123456789-.`, while C++ just stops converting once it hits an invalid character.
For waypoint **DC73B**, our `lat_string` is `45.03a2542` -- similar to the stray `s` creeping into a file that @michihdeu & I discussed upthread. Python finds the `a` in the string, records a datacheck error, and discards the point. C++ OTOH "successfully" parses the string as **45.03**, and puts the point in the Route object, quadtree, graph files, DB, and HB. In this case, a bit south of where it should be.
This is harder to spot than a waypoint at (0°,0°), which we've already decided we don't wanna keep around in the HB.
It makes sense to check for these types of errors in C++ too -- because there's the potential to find them. :) Having the C++ siteupdate program's output (graphs, logs, HB, whatever) match the Python program's output to the greatest degree practicable is a Good Thing.

**Comment by yakra** [comment] 2019-11-25 21:43
> Rather than lengthen the field to store more data, I think it makes sense to just drop the info column

Instead, I opted to display the offending `lat_string` or `lng_string` that we're unable to convert to numbers. Or if one or both of these strings is missing altogether, the text `MISSING_ARG(S)` will result. This way we still isolate the relevant info & display it to the user.
https://github.com/TravelMapping/DataProcessing/pull/265/commits/24a88a67647b73fe11b97414446ea663aa034462

Leaving this issue open because MALFORMED_URL is still not implemented in C++.

**Comment by yakra** [comment] 2019-12-17 23:08
Re-re-reopening this...
The odds of this happening are small, but, if both the latitude and longitude arguments of a URL contain invalid chars, we'll get two MALFORMED_URL errors for the same route & waypoint, only with different `Info` values. This means, both will show up in nearmatchfps.log, with the `CHANGETO` value listing the other entry's FP code. Mild wacky antics...

I see two ways around this:
* Change to MALFORMED_LAT & MALFORMED_LON, so that two errors for same same point will no longer register as *nearmatchfps* of one another.
* Just flag one error per waypoint. If lat is malformed, no need to test lon. Imperceptibly faster. Possibly less clear to the end user what's happening.

**Comment by michihdeu** [comment] 2019-12-18 07:06
> Change to MALFORMED_LAT & MALFORMED_LON

This!

**Closed** 2019-12-20 12:48 UTC
Labels: bug, robustness

**Comment by yakra** [comment] 2019-12-23 18:03
Not going to reopen the issue this time, but...

[I wrote:](https://github.com/TravelMapping/DataProcessing/issues/57#issuecomment-449693935)
>  We can have the error listed in dataceck, even with the ignored point not making it into the HB.

This is still true, but there's an added wrinkle now that datacheck.php tries to look up the waypoint label (which will be nonexistent for MALFORMED_URL, MALFORMED_LAT or MALFORMED_LON cases) in order to construct the HB link.

I'll test this out on lab2 to see how datacheck.php handles it.
