### ISSUE TITLE
Data check for updates.csv 

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#76] opened 2018-05-20 14:00 UTC
The file should be checked for invalid entries.
For instance, that the "root" column contains an existing path.

**Comment by michihdeu** [comment] 2018-05-20 14:02
I'm aware that any change to a root name could detect an old update entry with invalid link but I think that it's not a problem and the old entry should be modified, e.g. updating the link or removing the link.

**Comment by yakra** [comment] 2018-05-20 19:32
similar to https://github.com/TravelMapping/DataProcessing/issues/77#issuecomment-390501749
I'm thinking maybe just report malformed lines, and detect invalid routes and remove the link to the HB.

**Comment by jteresco** [comment] 2018-07-10 02:57
Duplicate of #68

**Closed** 2018-07-10 02:56 UTC
Labels: duplicate
