### ISSUE TITLE
unprocessedwpts.log lists mnonexistent files

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#31] opened 2016-09-21 15:08 UTC
there's a listing for **hwy_data/MA/usaima/ma.i090.wpt** in unprocessedwpts.log, but no such file or directory in the master repository.

**Comment by jteresco** [comment] 2016-09-21 19:34
That's caused by a test "mini-system" I have in my local copy that isn't in GitHub.  I should probably just get rid of it, but it's handy to have in case I need to track something down.

**Comment by jteresco** [comment] 2017-05-12 00:07
Closing this one.  That testing "usaima" system is not in my primary copy of the highway data any longer.

**Closed by jteresco** 2017-05-12 00:07 UTC
