### ISSUE TITLE
Check for non-ASCII entries in wpt, list files

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#41] opened 2016-12-18 15:53 UTC
The site update program should report and error and continue if a user's list file or a wpt file as non-ASCII characters.  Currently, the site update program crashes without an especially helpful error.  This might be best done as a pre-processing step or as the first task in a site update that will be noticed quickly rather than several minutes into the site update process.

**Comment by yakra** [comment] 2018-11-20 21:47
https://github.com/TravelMapping/UserData/blob/9ab420d7cc23d79b6d24f224c7186c88ee6ef777/list_files/lowenbrau.list

**Comment by michihdeu** [comment] 2018-12-21 19:32
> This leaves us with just AltLabels. Are there even any known AltLabels with non-ASCII characters currently?

I don't think so. They had likely made trouble in the past.

> If so, should they be left in for compatibility's sake? If not, should we prohibit them & make sure none creep in in the future?

I think that non-ASCII character are usually not added on purpose but by accident. And by accident, characters can appear everywhere in any file. If you check the file, you need to check the whole file.

**Comment by jteresco** [comment] 2018-12-21 21:47
Non-ASCII characters used to cause problems in site updates on FreeBSD before the utf-8 setting allowed that.  Notorious for this would be commented-out lines in systems.csv, where international characters are permitted.

**Comment by yakra** [comment] 2018-12-30 18:20
@yakra wrote:
> This leaves us with just AltLabels. Are there even any known AltLabels with non-ASCII characters currently?

Confirmed, there are none.

@michihdeu wrote:
> I think that non-ASCII character are usually not added on purpose but by accident.

This is true.

> And by accident, characters can appear everywhere in any file.

\*sigh\*, also true.
Sometimes I'll be editing some C++, and it won't compile (after pasting?), due to non-ASCII characters I can't see in pluma. I delete the offending line, retype it, and then compilesville, daddy-o.

@jteresco wrote:
> Non-ASCII characters used to cause problems in site updates on FreeBSD before the utf-8 setting allowed that.

Now that we use this option, non-ASCII characters are much less of a showstopper.

@michihdeu wrote:
> If you check the file, you need to check the whole file.

I'd say, only the necessary parts, just what would affect the functionality of the site.
URLs aren't stored; we just need to extract `lat_string` & `lng_string` and convert them to float. To that end, [http://madmagazine.com/?_**[%15]**_=43.661855&_**[%FF]**_=-70.270169](http://madmagazine.com/?%15=43.661855&%FF=-70.270169) is a valid URL, that can be parsed.

Primary labels are already checked.
This leaves us AltLabels.

I've tested out a version of siteupdate that expands the LABEL_INVALID_CHAR datacheck to AltLabels. On noreaster, it didn't add a noticeable amount of runtime, in one case even performing the data checks faster than the reference, siteupdate.py in #158.
Who knows what other processes noreaster may have been running at the same time though; I'll see if I get more deterministic results on BiggaTomato.

**Comment by yakra** [comment] 2018-12-30 19:58
> On noreaster, it didn't add a noticeable amount of runtime, in one case even performing the data checks faster than the reference, siteupdate.py in #158.
Who knows what other processes noreaster may have been running at the same time though; I'll see if I get more deterministic results on BiggaTomato.

On BiggaTomato:
0.2 s slower, best-case
0.4 s slower, average
0.5 s slower, worst-case

Not much harm in expanding LABEL_INVALID_CHAR to AltLabels, just to be safe.

What would be the more useful syntax for reporting them?
`me.us001;NH/ME;;;LABEL_INVALID_CHAR;+Foo#Bar`, or
`me.us001;+Foo#Bar;;;LABEL_INVALID_CHAR;`?
Right now, for primary labels only, the `Info` field is not used, E.G.
`chngd.g94;?;;;LABEL_INVALID_CHAR;`

**Comment by yakra** [comment] 2019-01-02 18:21
**Re .list files:**
> https://github.com/TravelMapping/UserData/blob/9ab420d7cc23d79b6d24f224c7186c88ee6ef777/list_files/lowenbrau.list
The final line, `ON ON405 ON/USA PorRd`, is followed by 1486 null `\0`s, before a final CRLF.

We can see that this line is not parsed:
http://travelmapping.net/logs/users/lowenbrau.log
http://travelmapping.net/hb/index.php?units=miles&u=lowenbrau&r=on.on405

**Comment by yakra** [comment] 2019-01-22 18:47
#176 fixes the problem with the trailing null zeros preventing **lowenbrau** from being credited for ON405.
Other than that, now that we have the `PYTHONIOENCODING='utf-8'` setting, as noted, non-ASCII characters aren't really a showstopper anymore.
Any non-ASCII character in a .list file would be either:
* in a comment, and thus ignored,
* in a line with <> 4 non-comment fields, and thus ignored,
* in the region or route fields, thus producing a normal `Unknown region/highway combo in line:` log error, or
* one of the waypoint labels, thus producing a normal `Waypoint label(s) not found in line:` log error.

I don't see much reason to keep this issue open anymore... anyone else?

**Comment by yakra** [comment] 2019-03-12 01:26
> * in a line with <> 4 non-comment fields, and thus ignored,

This would trigger the `Incorrect format line: ` error, and output the offending line to the .log

> * in the region or route fields, thus producing a normal `Unknown region/highway combo in line:` log error, or
> * one of the waypoint labels, thus producing a normal `Waypoint label(s) not found in line:` log error.

This can all result in control / non-ASCII characters in log files, which can prevent some text editors from reading them.

**Comment by yakra** [comment] 2019-03-12 05:10
**C++:** https://github.com/yakra/DataProcessing/commit/0e8298e864593d49a240b77bd23239228ca7b9bf

**Comment by yakra** [comment] 2020-04-14 18:47
Per https://github.com/TravelMapping/DataProcessing/issues/41#issuecomment-471809645, I made [some changes to the C++ version](https://github.com/TravelMapping/DataProcessing/commit/0e8298e864593d49a240b77bd23239228ca7b9bf) pretty early on.

Now, I'm thinking all this .list line checking is overkill.
> This can all result in control / non-ASCII characters in log files, which can prevent some text editors from reading them.

Do we care about this? Chances are, if it's a UTF-8 byte order mark or any international characters a traveler could type into their .list, any modern web browser will display the resulting .log line just fine, as should the same text editor the traveler used to create their .list.
Listing the actual original offending line in an error report in a log, rather than overwriting all non-ascii chars with a `?` will be nicer looking, and probably more immediately useful to the user.

* .wpt files have been addressed for some time now.
* with the `PYTHONIOENCODING='utf-8'` setting, .lists should be fine now too, with the existing error checks (the ones that go into user logs) sufficient to flag anything we truly want to check for.

Any objections if I decide non-ascii characters are OK in .list files, revert those C++ changes, and close this issue?

**Comment by jteresco** [comment] 2020-04-14 18:57
I agree a .log with the actual offending text will be more useful to a user.  I am fine with what you propose.

**Comment by yakra** [comment] 2020-04-14 21:01
> Chances are, if it's a **UTF-8 byte order mark** or any international characters a traveler could type into their .list, any modern web browser will display the resulting .log line just fine, as should the same text editor the traveler used to create their .list.

Those will only display right if at the beginning of a line. When displayed mid-line in a `Incorrect format line: ï»¿`, we see, well, that. Fixing #215 should make this a non-issue.

**Comment by yakra** [comment] 2020-04-15 01:13
> I agree a .log with the actual offending text will be more useful to a user.

Definitely the case for Incorrect format lines. Theoretically, the user can see that the number of fields in the line is wrong, and will know what to fix. Or maybe the line is just intended as a comment, without using `#`.
```DIFF
philimon.log:
3,6c3,6
< Incorrect format line: ======ΑΛΒΑΝΙΑ======
< Incorrect format line: ======ΑΝΔΟΡΡΑ======
< Incorrect format line: ======ΑΥΣΤΡΙΑ======
< Incorrect format line: ======ΒΕΛΓΙΟ======
---
> Incorrect format line: ======??????????????====== [line contains invalid character(s)]
> Incorrect format line: ======??????????????====== [line contains invalid character(s)]
> Incorrect format line: ======??????????????====== [line contains invalid character(s)]
> Incorrect format line: ======????????????====== [line contains invalid character(s)]
```
This junk isn't very helpful.
OTOH:
```DIFF
chaddean.log:
2c2
< Waypoint label(s) not found in line: FL FL44 FL19/98 US441
---
> Waypoint label(s) not found in line: FL FL44 FL19?/98 US441 [line contains invalid character(s)]
```
This looks a little nefarious. That's `0x1F`, the ascii field separator. No idea how it got in there, but...
Firefox & Chromium won't treat this as a regular text file; I'm prompted to download it & either open or save.
When chaddean opens it up in a text editor, it's possible he won't see any indication of the stray character at all. It may just be blank. He could see the error line and say, "What the heck? Looks like a perfectly fine waypoint label to me."
So, there could be some use for taking this approach when a control character is part of a region, route or label field.

These errors are rare; these are the only 2 user log files containing non-ascii characters. I'll fix the [Incorrect format line](https://github.com/TravelMapping/DataProcessing/commit/024426cbadae22875faeba5228d79ec4a5a66072#diff-94cf8ff30938f93555463a110df06dac) cases, and go no-build on the others for now while giving a bit more thought to how to handle them.

---
Heh -- lowerbrau.list somehow has a bunch of extra null `\0`s at the end of a file. If a null `\0` ever makes its way into the *middle* of a file, all hell will break loose. I hope that never happens.

**Comment by yakra** [comment] 2020-04-15 01:58
```DIFF
chaddean.log:
2c2
< Waypoint label(s) not found in line: FL FL44 FL19/98 US441
---
> Waypoint label(s) not found in line: FL FL44 FL19?/98 US441 [line contains invalid character(s)]
```
It makes sense to replace characters and add a note when control characters (< `0x20`) are included.

```DIFF
philimon.log:
49c49
< Unknown region/highway combo in line: //GRC EO03 Μπράλος Θερμοπύλες
---
> Unknown region/highway combo in line: //GRC EO03 ?????????????? ???????????????????? [line contains invalid character(s)]
```
But it does not make sense to replace characters > `0x7F`, which are probably going to be part of international characters.

**Comment by yakra** [comment] 2020-04-15 14:37
> Heh -- lowenbrau.list somehow has a bunch of extra null `\0`s at the end of a file. If a null `\0` ever makes its way into the *middle* of a file, all hell will break loose. I hope that never happens.

Going full bore with mitigating any null `\0`s is overkill when as it stands this is essentially a fix for an oddity in a single file -- multiple or much more complicated `strip`s, and then treating them as a delimiter ...
On the C++ side, we're not using `strtok` to separate lines anymore, so a potential rewrite would be simpler. But still.

Similar to removing the BOM from the first line only, we can `rstrip('\x00')` from the last line only, sand save some processing time on the rest.

**Comment by yakra** [comment] 2020-04-15 18:38
No difference in speed. I'll keep it about as it is, for that extra little bit of robustness.

**Closed** 2020-04-16 03:21 UTC
Labels: enhancement, pending, robustness
