### ISSUE TITLE
Failure in siteupdate.py reported much later

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#162] opened 2019-01-06 03:34 UTC
Recent changes have meant that when a data error slips in, the "ABORTING due to N errors" doesn't happen until after (the time consuming) generation of all the subgraphs.  I had gotten used to being able to ignore the site update process once graph generation started.  I'd like to see about getting that ABORTING condition moved back earlier so I have a better chance to notice the problem.  I just about was calling it a night when I noticed tonight's update had failed.  I'll try to check this out soon but wouldn't be sad if @yakra beat me to it.

**Comment by yakra** [comment] 2019-01-06 07:19
The final call to `el.add_error` is after reading datacheckfps.csv, if we're unable to parse a datacheckfps.csv line.
We could move https://github.com/TravelMapping/DataProcessing/blob/103c84da00126c18c7dbfbf4872c26b259a17731/siteupdate/python-teresco/siteupdate.py#L3054-L3080
earlier, and just have the info hang around during graph generation until we need it.
(It's a smaller & simpler diff than, say, moving all the subgraph generation to the very end...)
Makes sense to me to move it before
https://github.com/TravelMapping/DataProcessing/blob/103c84da00126c18c7dbfbf4872c26b259a17731/siteupdate/python-teresco/siteupdate.py#L2863-L2864
and keep all the graph generation-related code together in one place (as opposed to moving it immediately before subgraph generation, after master graph setup).

If we wanted to move this even earlier in the process, it could go after reading the WPT files (the previous call to `el.add_error` is here), before sorting waypoints in Quadtree.

**Comment by michihdeu** [comment] 2019-01-06 07:38
Isn't it possible to check whether there is an error and abort after wpt files are read? Most of the errors happen here (caused by csv file errors). The check for errors can be done later again.

**Comment by jteresco** [comment] 2019-01-06 15:06
Let's put it as late as possible to catch as many current and future unrecoverable errors, so right before graph generation.

**Closed** 2019-01-07 18:54 UTC
Labels: code organization, pending, usability
